export enum MyPageTab {
  INFO = "INFO",
  RESERVATION_HISTORIES = "RESERVATION_HISTORIES",
  SCRAPED_PERFORMANCES = "SCRAPED_PERFORMANCES",
  PERFORMANCE_DASHBOARD = "PERFORMANCE_DASHBOARD",
  COUPONS = "COUPONS",
  SETTLEMENT_DASHBOARD = "SETTLEMENT_DASHBOARD",
  POINTS = "POINTS",
}
